### ISSUE TITLE
Updating to uniffi 0.24

### ISSUE THREAD

**Issue by dignifiedquire** [NordSecurity/uniffi-bindgen-go#12]
Hey, I was wondering what the status of this is, I am making a lot of use of the new `bytes` and other types that 0.24 introduced.

**Comment by arg0d** [comment]
Hey, its in our backlog, but we have other more important priorities right now.

**Comment by dignifiedquire** [comment]
thanks for the heads up, I expect to continue work on it in #13, so hopefully we can all benefit from it :)

**Comment by arg0d** [comment]
Fixed in favor of [upgrade to 0.25](https://github.com/NordSecurity/uniffi-bindgen-go/pull/26).
