### ISSUE TITLE
Support for docstrings

### ISSUE THREAD

**Issue by dignifiedquire** [NordSecurity/uniffi-bindgen-go#25]
With https://github.com/mozilla/uniffi-rs/pull/1493 getting close to be merged, I was wondering if there was already a branch that supported docstrings and/or if you are planning to implement this

**Comment by arg0d** [comment]
All branches in [our fork starting with 0.23](https://github.com/NordSecurity/uniffi-rs/releases) support docstrings.

Its just somehow Go got left behind :smiling_face_with_tear:

**Comment by dignifiedquire** [comment]
@arg0d will you have time to work on this? otherwise I will try to look into adding support

**Comment by arg0d** [comment]
If you have time to spare, sure! Help would be awesome :)

**Comment by dignifiedquire** [comment]
first version here: https://github.com/NordSecurity/uniffi-bindgen-go/pull/33

**Comment by kegsay** [comment]
There seems to be 2 docstring impls now - uniffi 0.26 landed it as well as NordSecurity's fork of uniffi-rs https://github.com/NordSecurity/uniffi-rs?tab=readme-ov-file#ad-hoc-features - are they compatible with each other? If so, if we updated to 0.26 could we drop the uniffi-rs fork?

**Comment by arg0d** [comment]
Yes, the upstream should have identical docstrings implementation in `mozilla/uniffi-rs:v0.26.0`.
