### ISSUE TITLE
concurrentHandleMap.tryGet is not safe

### ISSUE THREAD

**Issue by kegsay** [NordSecurity/uniffi-bindgen-go#28]
https://github.com/NordSecurity/uniffi-bindgen-go/blob/62347acdf3c00efc54398ef6f0fc3f93e9578df4/bindgen/templates/CallbackInterfaceRuntime.go#L46-L48

Can cause `fatal error: concurrent map read and map write` as the read is not protected with a mutex.

I'd suggest replacing `lock          sync.Mutex` with a `sync.RWMutex`.

**Comment by arg0d** [comment]
I think concurrentHandleMap can be replaced entirely by [using `cgo.Handle`](https://github.com/NordSecurity/uniffi-bindgen-go/issues/18) instead.

**Comment by arg0d** [comment]
Thanks for the report, good catch :+1:
