### ISSUE TITLE
Add extra information on `LD_LIBRARY_PATH` to readme 

### ISSUE THREAD

**Issue by mfahampshire** [NordSecurity/uniffi-bindgen-go#38]
As outlined and solved in [this](https://github.com/NordSecurity/uniffi-bindgen-go/issues/32) issue there is a little extra work that has to be done to go from using `uniffi-bindgen-go` to having a file you can import and use. 

I would be happy to create a PR to add these instructions, as well as a small example of how to test the file locally, to the README or docs, but I wanted to check (a) whether this would be something you'd want, and (b) where you'd prefer this information to go (perhaps alongside the other docs files) before opening a PR.

**Comment by arg0d** [comment]
Sure, appending README.md sounds good.

**Comment by BatmanAoD** [comment]
@mfahampshire did you mean to link to a different issue?

**Comment by mfahampshire** [comment]
I did - amending the PR now @BatmanAoD

**Comment by mfahampshire** [comment]
closing as readme PR #39 was merged
